- name: Add key for rabbitmq apt repository
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present

- name: Add rabbitmq official apt repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Install rabbitmq-server
  apt: pkg=rabbitmq-server state={{ apt_package_state }} install_recommends=yes

- name: Stop rabbitmq server
  service: name=rabbitmq-server state=stopped enabled=no
